### ISSUE TITLE
Counter metadata seems wrong

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#57]
http://dev.library.kiwix.org/wikihow_eng_all_2021-08/M/Counter

**Comment by rgaudin** [comment]
@kelson42, I don't seem to have any other way but to run an old version of kiwix-serve to access the Counter… Even zimdump doesn't return it.

I can't find any issue on libkiwix nor kiwix-tools about it but I believe we talked about it in the past.

**Comment by kelson42** [comment]
@mgautierfr what is the strayegy to dump/inspect the Metadata namespace?

**Comment by mgautierfr** [comment]
> what is the strayegy to dump/inspect the Metadata namespace

Using the libzim : [`Archive::getMetadataKeys`](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html#_CPPv4NK3zim7Archive15getMetadataKeysEv) and [`Archive::getMetadata`](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html#_CPPv4NK3zim7Archive11getMetadataERKNSt6stringE)
We have them in python-libzim (https://github.com/openzim/python-libzim/blob/master/libzim/wrapper.pyx#L534-L550).

With kiwix-serve we have the `meta` endpoints `http://dev.library.kiwix.org/meta?content=wikihow_eng_all_2021-08&content=Counter`. But the `Counter` metadata is not handled, probably because I forgot about it when I've implemented this (https://github.com/kiwix/libkiwix/blob/master/src/server/internalServer.cpp#L383-L432)
It can be easily added.

---

It worth mentionning that, in the master version of the libzim, `M/Counter` is automatically added. Scrappers MUST NOT add them and if there is a bug, it may be in libzim itself.

**Comment by rgaudin** [comment]
@mgautierfr thanks for the answer. I forgot that `Counter` is a *regular* metadata. Since we're not writing it, I though it was handled differently. I do have access to it via pylibzim reader.

Regarding kiwix-serve, we do have access to the illustration: http://dev.library.kiwix.org/meta?name=Illustration_48x48@1&content=wikihow_tr_all_2021-09

~~But that's about it. `Title` for instance is not available using a similar url: http://dev.library.kiwix.org/meta?name=Title&content=wikihow_tr_all_2021-09~~

Ah! The metadata key is lowercased in the endpoint! Wasn't the case before. So `&name=title` gives the title: http://dev.library.kiwix.org/meta?name=title&content=wikihow_tr_all_2021-09

Regarding this ticket, it has nothing to do with the Counter. We're just providing too-generic mimetypes.
