### ISSUE TITLE
Include releated links in scraping list

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#70]
It seems there are cross articles links which are missing, see with WikiHow TR:
```
- ./Ayaktaki-Su-Toplamas%C4%B1-Nas%C4%B1l-Tedavi-Edilir
(Ayaktaki-Su-Toplaması-Nasıl-Tedavi-Edilir) were not found in article Kasık-Mantarı-Nasıl-Tedavi-Edilir
  The following links:
- ./Etin-Bozuldu%C4%9Fu-Nas%C4%B1l-Anla%C5%9F%C4%B1l%C4%B1r
(Etin-Bozulduğu-Nasıl-Anlaşılır) were not found in article Kıymanın-Bozulduğu-Nasıl-Anlaşılır
  The following links:
- ./Ak%C4%B1ll%C4%B1-Saat-Android%27le-Nas%C4%B1l-E%C5%9Fle%C5%9Ftirilir
- ./Ak%C4%B1ll%C4%B1-Saat-Android%27le-Nas%C4%B1l-E%C5%9Fle%C5%9Ftirilir
(Akıllı-Saat-Android'le-Nasıl-Eşleştirilir) were not found in article Microsoft-Office-Nasıl-Yüklenir
  The following links:
- ./Ak%C4%B1ll%C4%B1-Saat-Android%27le-Nas%C4%B1l-E%C5%9Fle%C5%9Ftirilir
- ./Ak%C4%B1ll%C4%B1-Saat-Android%27le-Nas%C4%B1l-E%C5%9Fle%C5%9Ftirilir
(Akıllı-Saat-Android'le-Nasıl-Eşleştirilir) were not found in article Microsoft-Word-Belgesi-PDF-Formatına-Nasıl-Dönüştürülür
  The following links:
- ./Etin-Bozuldu%C4%9Fu-Nas%C4%B1l-Anla%C5%9F%C4%B1l%C4%B1r
(Etin-Bozulduğu-Nasıl-Anlaşılır) were not found in article Yumurtanın-Bozulup-Bozulmadığı-Nasıl-Anlaşılır
  The following links:
- ./Aloe-Vera-Bitkisine-Nas%C4%B1l-Bak%C4%B1l%C4%B1r
(Aloe-Vera-Bitkisine-Nasıl-Bakılır) were not found in article Zehirli-Sarmaşık-Nasıl-Anlaşılır
  The following links:
- ./Aloe-Vera-Bitkisine-Nas%C4%B1l-Bak%C4%B1l%C4%B1r
(Aloe-Vera-Bitkisine-Nasıl-Bakılır) were not found in article Ananas-Nasıl-Yetiştirilir
  The following links:
- ./Bir-Haftada-Kal%C3%A7a-Nas%C4%B1l-B%C3%BCy%C3%BCt%C3%BCl%C3%BCr
(Bir-Haftada-Kalça-Nasıl-Büyütülür) were not found in article Bandana-Nasıl-Bağlanır
  The following links:
```

**Comment by rgaudin** [comment]
@kelson42, please create more focus issues so it's easier to triage and fix. 

Regarding this particular issue, it appears not all articles are listed in their category.  For instance [Ayaktaki Su Toplaması Nasıl Tedavi Edilir](https://www.wikihow.com.tr/Ayaktaki-Su-Toplamas%C4%B1-Nas%C4%B1l-Tedavi-Edilir) has [Sağlık](https://www.wikihow.com.tr/Kategori:Sa%C4%9Fl%C4%B1k) Category but is not listed in the 5 pages or articles for that category…

I don't know if this is specific to that turkish version (the fact that this category has a reference loop makes me doubt they're rigorously watching it).

There are a couple of ways to get around that:

- Scrape content based on API results instead of walking the categories. This would allow removing any dead link but is a big change that is probably too late to take. Also, we're not 100% sure the API will provide what we want or that it won't break in the near future. And we don't know the internals of wikiHow. There might be stuff on the main namespace that are not displayed for a reason.
- Add *related links* to the scraping list while parsing articles. It's a quick fix that would probably fix close to all dead links but since we don't have a full list of expected articles before end, it won't be possible to guarantee there will be no dead link.

Let's go with the second approach that's a lot safer and easier to implement ATM.

**Comment by kelson42** [comment]
If we finally achieve to fix this kind of problem without relying on the API, I would be surprised. But probably worth a try.
